# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
     - task: JavaToolInstaller@0
       inputs:
         versionSpec: '20'
         jdkArchitectureOption: 'x64'
         jdkSourceOption: 'PreInstalled'
     - task: CmdLine@2
       inputs:
         script: |
           echo Write your commands here
           sudo apt update
           wget https://download.oracle.com/java/21/latest/jdk-21_linux-aarch64_bin.tar.gz
           
           tar xzf jdk-21_linux-aarch64_bin.tar.gz
           
           sudo mv jdk-21 /usr/local/
           
           nano ~/.bashrc
           
           export JAVA_HOME=/usr/local/jdk-21
           export PATH=$PATH:$JAVA_HOME/bin
           
           source ~/.bashrc
           
           java -version
           echo Hello world
