apiVersion: apps/v1
kind: Deployment
metadata:
  name: nearby-service-app
  labels:
    app: nearby-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nearby-service-app
  template:
    metadata:
      labels:
        app: nearby-service-app
    spec:
      containers:
        - name: nearby-service-app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 9193